functions <- list(
  batch_correct_counts = list(
    moo_input_rds = "moo.rds",
    moo_output_rds = "moo.rds",
    count_type = "norm",
    sub_count_type = "voom",
    sample_id_colname = NULL,
    feature_id_colname = NULL,
    samples_to_include = NULL,
    covariates_colnames = "Group",
    batch_colname = "Batch",
    label_colname = NULL,
    colors_for_plots = NULL,
    print_plots = TRUE,
    save_plots = TRUE,
    plots_subdir = "batch"
  ),
  clean_raw_counts = list(
    moo_input_rds = "moo.rds",
    moo_output_rds = "moo.rds",
    count_type = "raw",
    sample_id_colname = NULL,
    feature_id_colname = NULL,
    samples_to_rename = c(""),
    cleanup_column_names = TRUE,
    split_gene_name = TRUE,
    aggregate_rows_with_duplicate_gene_names = TRUE,
    gene_name_column_to_use_for_collapsing_duplicates = "",
    print_plots = TRUE,
    save_plots = TRUE
  ),
  create_multiOmicDataSet_from_files = list(
    moo_output_rds = "moo.rds",
    sample_meta_filepath = NULL,
    feature_counts_filepath = NULL,
    count_type = "raw",
    sample_id_colname = NULL,
    feature_id_colname = NULL
  ),
  filter_diff = list(
    moo_input_rds = "moo.rds",
    moo_output_rds = "moo.rds",
    feature_id_colname = NULL,
    significance_column = "adjpval",
    significance_cutoff = 0.05,
    change_column = "logFC",
    change_cutoff = 1,
    filtering_mode = "any",
    include_estimates = c("FC", "logFC", "tstat", "pval", "adjpval"),
    round_estimates = TRUE,
    rounding_decimal_for_percent_cells = 0,
    contrast_filter = "none",
    contrasts = c(),
    groups = c(),
    groups_filter = "none",
    label_font_size = 6,
    label_distance = 1,
    y_axis_expansion = 0.08,
    fill_colors = c("steelblue1", "whitesmoke"),
    pie_chart_in_3d = TRUE,
    bar_width = 0.4,
    draw_bar_border = TRUE,
    plot_type = "bar",
    plot_titles_fontsize = 12,
    print_plots = TRUE,
    save_plots = TRUE,
    plots_subdir = file.path("diff", "filt")
  ),
  diff_counts = list(
    moo_input_rds = "moo.rds",
    moo_output_rds = "moo.rds",
    count_type = "filt",
    sub_count_type = NULL,
    sample_id_colname = NULL,
    feature_id_colname = NULL,
    samples_to_include = NULL,
    covariates_colnames = NULL,
    contrast_colname = NULL,
    contrasts = NULL,
    input_in_log_counts = FALSE,
    return_mean_and_sd = FALSE,
    voom_normalization_method = "quantile",
    print_plots = TRUE,
    save_plots = TRUE,
    plots_subdir = "diff"
  ),
  filter_counts = list(
    moo_input_rds = "moo.rds",
    moo_output_rds = "moo.rds",
    count_type = "clean",
    feature_id_colname = NULL,
    sample_id_colname = NULL,
    group_colname = "Group",
    label_colname = NULL,
    samples_to_include = NULL,
    minimum_count_value_to_be_considered_nonzero = 8,
    minimum_number_of_samples_with_nonzero_counts_in_total = 7,
    minimum_number_of_samples_with_nonzero_counts_in_a_group = 3,
    use_cpm_counts_to_filter = TRUE,
    use_group_based_filtering = FALSE,
    principal_component_on_x_axis = 1,
    principal_component_on_y_axis = 2,
    legend_position_for_pca = "top",
    point_size_for_pca = 1,
    add_label_to_pca = TRUE,
    label_font_size = 3,
    label_offset_y_ = 2,
    label_offset_x_ = 2,
    samples_to_rename = c(""),
    color_histogram_by_group = FALSE,
    set_min_max_for_x_axis_for_histogram = FALSE,
    minimum_for_x_axis_for_histogram = -1,
    maximum_for_x_axis_for_histogram = 1,
    legend_position_for_histogram = "top",
    legend_font_size_for_histogram = 10,
    number_of_histogram_legend_columns = 6,
    colors_for_plots = NULL,
    print_plots = TRUE,
    save_plots = TRUE,
    interactive_plots = FALSE,
    plots_subdir = "filt"
  ),
  normalize_counts = list(
    moo_input_rds = "moo.rds",
    moo_output_rds = "moo.rds",
    count_type = "filt",
    norm_type = "voom",
    feature_id_colname = NULL,
    samples_to_include = NULL,
    sample_id_colname = NULL,
    group_colname = "Group",
    label_colname = NULL,
    input_in_log_counts = FALSE,
    voom_normalization_method = "quantile",
    samples_to_rename = c(""),
    add_label_to_pca = TRUE,
    principal_component_on_x_axis = 1,
    principal_component_on_y_axis = 2,
    legend_position_for_pca = "top",
    label_offset_x_ = 2,
    label_offset_y_ = 2,
    label_font_size = 3,
    point_size_for_pca = 8,
    color_histogram_by_group = TRUE,
    set_min_max_for_x_axis_for_histogram = FALSE,
    minimum_for_x_axis_for_histogram = -1,
    maximum_for_x_axis_for_histogram = 1,
    legend_font_size_for_histogram = 10,
    legend_position_for_histogram = "top",
    colors_for_plots = NULL,
    print_plots = TRUE,
    save_plots = TRUE,
    interactive_plots = FALSE,
    plots_subdir = "norm"
  )
)

names(functions) %>%
  lapply(\(func_name) {
    func_args <- functions[[func_name]]
    filename <- here::here(
      'inst',
      'extdata',
      'json_args',
      'defaults',
      glue::glue("{func_name}.json")
    )
    jsonlite::write_json(
      func_args,
      filename,
      auto_unbox = TRUE,
      pretty = TRUE,
      null = 'null',
      na = 'null'
    )
    return(filename)
  })
