---
title: "Visualization with built-in plots"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{visualization}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
options(rmarkdown.html_vignette.check_title = FALSE)
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.width = 5,
  fig.height = 4
)
```

```{r setup}
library(MOSuite)
```

## Default plots from each step

### clean

```{r nidap_data_clean}
moo <- create_multiOmicDataSet_from_dataframes(
  sample_metadata = as.data.frame(nidap_sample_metadata),
  counts_dat = as.data.frame(nidap_raw_counts)
) %>%
  clean_raw_counts(print_plots = TRUE)
```
```{r nidap_filter}
moo %<>%
  filter_counts(group_colname = "Group", print_plots = TRUE)
```

### normalize

```{r nidap_norm}
moo %<>%
  normalize_counts(group_colname = "Group", print_plots = TRUE)
```

### batch correct

```{r nidap_batch}
moo %<>% batch_correct_counts(
  covariates_colname = "Group",
  batch_colname = "Batch",
  label_colname = "Label",
  print_plots = TRUE
)
```


## Customize plots

TODO
- show how to use individual plotting functions
- how to customize & override default color palettes
- how to customize ggplot objects

### 3D PCA

```{r pca_3D}
plot_pca_3d(moo@counts$batch,
  moo@sample_meta,
  group_colname = "Group",
  label_colname = "Label",
  color_values = moo@analyses[["colors"]][["Group"]]
)
```

## Expression Heatmap

```{r expr_heatmap}
plot_expr_heatmap(moo@counts[["norm"]][["voom"]], moo@sample_meta)
```
