ARG R_VERSION=4.4
FROM rocker/tidyverse:${R_VERSION}

ARG R_VERSION
ENV R_VERSION=${R_VERSION}

# build time variables
ARG BUILD_DATE="000000"
ENV BUILD_DATE=${BUILD_DATE}
ARG BUILD_TAG="000000"
ENV BUILD_TAG=${BUILD_TAG}
ARG REPONAME="000000"
ENV REPONAME=${REPONAME}

# install python, pip, pre-commit, zsh
RUN apt-get update && apt-get upgrade -y && \
    apt-get install -y --no-install-recommends \
      openssh-client \
      python3-pip python3-dev python3-venv && \
    python3 -m venv /opt/pyenv && \
    /opt/pyenv/bin/pip3 install --no-cache-dir --upgrade pip3 && \
    /opt/pyenv/bin/pip3 install --no-cache-dir pre-commit && \
    sh -c "$(wget -O- https://github.com/deluan/zsh-in-docker/releases/download/v1.2.1/zsh-in-docker.sh)" -- \
      -t robbyrussell -p git -p ssh-agent && \
      chsh -s ~/.zshrc && \
    rm -rf ~/.cache/pip* && \
    apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/* && \
    apt-get autoclean && apt-get autoremove -y && \
    rm -rf /var/lib/{apt,dpkg,cache,log}/

ENV PATH="/opt/pyenv/bin:/opt/:$PATH"

# install package dependencies, but not the R package itself
# using --mount avoids copying the context into the image
RUN --mount=type=bind,source=.,target=/opt/MOSuite \
    Rscript /opt/MOSuite/docker/install_dev.R
