name: Add repo name label

on:
  issues:
    - opened
  pull_request:
    - opened

jobs:
  add_label:
    uses: CCBR/.github/.github/workflows/add_reponame_issue_label.yml@v0.2.0
    secrets: inherit
